from typing import TypedDict, Annotated
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.prompts import MessagesPlaceholder
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode, tools_condition
from langgraph.checkpoint.memory import MemorySaver

from langchain_core.messages import SystemMessage

from config import llm
from prompts import agent_prompt
from tools import available_tools

class AgentState(TypedDict):
    messages: Annotated[list, add_messages]
    reflection: str


llm_with_tools = llm.bind_tools(
    available_tools,
    tool_choice="auto"
)

def agent_node(state):

    messages = [
        SystemMessage(content=agent_prompt),
        *state["messages"]
    ]

    response = llm_with_tools.invoke(messages)

    return {
        "messages": [response]
    }

reflection_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
            You are a quality assurance reviewer.

            Review the final answer generated by the financial assistant.

            Check:
            - Accuracy
            - Completeness
            - Tool usage
            - Data masking compliance
            - Missing information

            Return a concise reflection.
            """
        ),
        MessagesPlaceholder("messages")
    ]
)

reflector = reflection_prompt | llm
def reflection_node(state: AgentState):

    print("\n--- REFLECTION NODE ---")

    response = reflector.invoke(
        {
            "messages": state["messages"]
        }
    )

    print(response.content)

    return {
        "reflection": response.content or ""
    }

def route_after_agent(state):

    last_message = state["messages"][-1]

    if hasattr(last_message, "tool_calls") and last_message.tool_calls:
        return "tools"

    return "reflector"

graph = StateGraph(AgentState)

graph.add_node("agent", agent_node)
graph.add_node("tools", ToolNode(available_tools))
graph.add_node(
    "reflector",
    reflection_node
)
graph.add_edge(START, "agent")

graph.add_conditional_edges(
    "agent",
    route_after_agent,
    {
        "tools": "tools",
        "reflector": "reflector"
    }
)

graph.add_edge(
    "tools",
    "agent"
)
graph.add_edge("reflector", END)

compiled_graph = graph.compile(
    checkpointer=MemorySaver()
)