
# output_formatter.py

def format_response(user_request, final_answer):

    return {
        "user_request": user_request,
        "plan_summary": "Generated by agent",
        "tools_used": [],
        "tool_result_summary": "See agent response",
        "reflection_summary": "Information gathered successfully",
        "final_answer": final_answer,
        "memory_used": False,
        "write_action_performed": False
    }