# Generated by Django 4.2.8 on 2026-08-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('report_type', models.CharField(max_length=200)),
                ('sent_at', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(choices=[('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Delivered', max_length=20)),
                ('summary_preview', models.TextField()),
                ('follow_up_actions_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutedAction',
            fields=[
                ('action_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('action_code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Executed', 'Executed'), ('Failed', 'Failed')], default='Executed', max_length=20)),
                ('channel', models.CharField(max_length=100)),
                ('execution_log', models.TextField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sender_email', models.EmailField(max_length=254)),
                ('report_type', models.CharField(max_length=200)),
                ('cron', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Paused', 'Paused')], default='Active', max_length=20)),
                ('next_run', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('transfer_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('priority', models.CharField(default='Normal', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('courier_partner', models.CharField(max_length=200)),
                ('tracking_number', models.CharField(max_length=100, unique=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
